name: Build for Raspberry Pi (Raspbian Bullseye, Python 3.9)

on: [push, pull_request]

jobs:
  build-raspi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build inside Raspberry Pi-like container
        run: |
          docker run --rm \
            --platform linux/arm/v7 \
            -v "${{ github.workspace }}:/src" \
            -w /src \
            arm32v7/python:3.9-bullseye \
            bash -c "
              apt-get update \
              && apt-get install -y python3-pyinstaller gcc \
              && pip3 install -r requirements.txt \
              && pyinstaller main.py
            "

      - name: Upload Raspberry Pi binary
        uses: actions/upload-artifact@v4
        with:
          name: raspi-bin
          path: dist/main
