name: Build for Raspberry Pi (Raspbian Bullseye)

on: [push, pull_request]

jobs:
  build-raspi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU + Docker Buildx
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build inside Raspberry Pi-like container
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src \
            --platform linux/arm/v7 \
            balenalib/raspberrypi-debian-python:bullseye-python3.9 \
            bash -c "apt-get update && apt-get install -y pyinstaller && pip3 install -r requirements.txt && pyinstaller main.py"

      - name: Upload Raspberry Pi binary
        uses: actions/upload-artifact@v4
        with:
          name: raspi-bin
          path: dist/main
