name: Build All Platforms

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller
      - run: build.bat
      - uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/main.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller
      - run: build.bat
      - uses: actions/upload-artifact@v4
        with:
          name: ./build.sh
          path: dist/main

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pyinstaller
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: macos-bin
          path: dist/main
